
import { Product, Review } from './types';

export const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
};

export const FARMERS = [
  {
    id: '1',
    name: 'Kebun Kerinci',
    location: 'Kerinci, Jambi',
    distance: '15km',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=400&auto=format&fit=crop' // Tea plantation / Highland
  },
  {
    id: '2',
    name: 'Tani Organik Muaro',
    location: 'Muaro Jambi',
    distance: '20km',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?q=80&w=400&auto=format&fit=crop' // Green fields
  },
  {
    id: '3',
    name: 'Petani Merangin',
    location: 'Merangin, Jambi',
    distance: '22km',
    image: 'https://images.unsplash.com/photo-1533241242337-774b73273822?q=80&w=400&auto=format&fit=crop' // Rice terraces
  },
  {
    id: '4',
    name: 'Sayur Sarolangun',
    location: 'Sarolangun',
    distance: '25km',
    image: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?q=80&w=400&auto=format&fit=crop' // Vegetables
  },
  {
    id: '5',
    name: 'Kebun Batanghari',
    location: 'Batanghari',
    distance: '30km',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=400&auto=format&fit=crop' // Agriculture landscape
  },
  {
    id: '6',
    name: 'Ladang Tj. Jabung',
    location: 'Tanjung Jabung Barat',
    distance: '35km',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80&w=400&auto=format&fit=crop' // Farm field
  },
  {
    id: '7',
    name: 'Tani Bungo',
    location: 'Muara Bungo',
    distance: '42km',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=400&auto=format&fit=crop' // Fresh Fruits
  },
  {
    id: '8',
    name: 'Petani Tebo',
    location: 'Muara Tebo',
    distance: '48km',
    image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?q=80&w=400&auto=format&fit=crop' // Crops
  },
  {
    id: '9',
    name: 'Kebun Sungai Penuh',
    location: 'Sungai Penuh',
    distance: '55km',
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?q=80&w=400&auto=format&fit=crop' // Nature
  },
  {
    id: '10',
    name: 'Hijau Muaro Jambi',
    location: 'Sengeti',
    distance: '12km',
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?q=80&w=400&auto=format&fit=crop' // Greenhouse/Farm
  }
];

export const TRANSLATIONS: any = {
  en: {
    home: "Home",
    marketplace: "Marketplace",
    aiChatbot: "AI Chatbot",
    sellerDemo: "Seller Mode",
    searchPlaceholder: "Search products...",
    copyright: "© 2025 RANTU. All rights reserved.",
    aboutUs: "About Us",
    contact: "Contact",
    faq: "FAQ",
    terms: "Terms of Service",
    dashboard: "Dashboard",
    orders: "Orders",
    products: "Products",
    analytics: "Analytics",
    backToBuyer: "Back to Buyer Mode",
    hero1Title: "Weekend Harvest Sale: 20% Off All Berries",
    hero1Sub: "Enjoy the freshest picks of the season. Limited time offer!",
    hero2Title: "Fresh Mangoes Arriving Next Week!",
    hero2Sub: "Get ready for the sweetest mangoes, direct from the farm.",
    hero3Title: "Organic Greens Now In Stock",
    hero3Sub: "From crisp lettuce to kale, get your daily greens here.",
    discoverFarmers: "Discover Farmers Near You",
    away: "away",
    freshPicks: "Fresh Picks & Best Sellers",
    viewAll: "View All",
    productCatalog: "Product Catalog",
    browseText: "Browse the freshest products directly from local farmers.",
    sortBy: "Sort by: Newly Added",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    categories: {
      All: "All",
      Vegetables: "Vegetables",
      Fruits: "Fruits",
      Grains: "Grains",
      Spices: "Spices"
    },
    from: "from",
    addToCart: "Add to Cart",
    noProducts: "No products found in this category.",
    viewAllProducts: "View all products",
    shoppingCart: "Shopping Cart",
    myCart: "My Shopping Cart",
    items: "items",
    product: "Product",
    price: "Price",
    quantity: "Quantity",
    total: "Total",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    estimatedShipping: "Estimated Shipping",
    estimatedTaxes: "Estimated Taxes",
    grandTotal: "Grand Total",
    proceedToCheckout: "Proceed to Checkout",
    continueShopping: "Continue Shopping",
    reviews: "reviews",
    preOrder: "Pre-Order",
    viewProfile: "View Profile",
    welcomeBack: "Welcome back, here's a summary of your store activity today.",
    totalSales: "Total Sales Today",
    newOrders: "New Orders",
    activeBalance: "Active Balance",
    vsYesterday: "vs yesterday",
    vsLastWeek: "vs last week",
    awaitingDispatch: "awaiting dispatch",
    commodityTrends: "Commodity Price Trends",
    aiInsight: "AI Insight",
    aiInsightText: "Chili price predicted to rise by 8% in the next 3 days.",
    aiInsightSub: "Consider adjusting your stock or pricing strategy to maximize profit.",
    adjustPricing: "Adjust Pricing",
    shipping: "Shipping",
    payment: "Payment",
    shippingDetails: "Shipping Details",
    recipientInfo: "Recipient Information",
    recipientName: "Recipient Name",
    phoneNumber: "Phone Number",
    fullAddress: "Full Address",
    pinLocation: "Pin Your Exact Location",
    dragPin: "Drag the pin or search for your address for precise delivery.",
    saveAndContinue: "Save and Continue",
    securePayment: "Secure Payment",
    selectPayment: "Select Payment Method",
    bankTransfer: "Bank Transfer",
    payBank: "Pay via a secure bank transfer",
    ewallet: "E-Wallet",
    payEwallet: "Pay with GoPay, OVO, etc.",
    confirmPay: "Confirm and Pay",
    promo: "Promo Code (FARM2TABLE)",
    confirmOrder: "Confirm Your Order",
    shippingTo: "Shipping To",
    edit: "Edit",
    confirmPayment: "Confirm Payment",
    allFarmers: "All Farmers",
    farmersSubtitle: "Meet the local heroes growing your food.",
    deliveryDate: "Preferred Delivery Date",
    deliveryDateNote: "Select a date for your pre-order delivery (min. 2 days from today).",
    addNewProduct: "Add New Product",
    auth: {
      welcome: "Welcome to RANTU",
      subtitle: "Connecting the Farm to Your Table",
      login: "Login",
      register: "Register",
      fullName: "Full Name",
      email: "Email Address",
      password: "Password",
      or: "OR",
      continueGoogle: "Continue with Google",
      continueFacebook: "Continue with Facebook",
      haveAccount: "Already have an account?",
      noAccount: "Don't have an account?",
      role: "I am a",
      buyer: "Buyer",
      seller: "Farmer/Seller"
    }
  },
  id: {
    home: "Beranda",
    marketplace: "Pasar",
    aiChatbot: "Chatbot AI",
    sellerDemo: "Mode Penjual",
    searchPlaceholder: "Cari produk...",
    copyright: "© 2025 RANTU. Hak cipta dilindungi.",
    aboutUs: "Tentang Kami",
    contact: "Kontak",
    faq: "FAQ",
    terms: "Syarat Layanan",
    dashboard: "Dasbor",
    orders: "Pesanan",
    products: "Produk",
    analytics: "Analitik",
    backToBuyer: "Kembali ke Mode Pembeli",
    hero1Title: "Panen Raya Akhir Pekan: Diskon 20% Semua Buah",
    hero1Sub: "Nikmati hasil panen paling segar musim ini. Penawaran terbatas!",
    hero2Title: "Mangga Segar Tiba Minggu Depan!",
    hero2Sub: "Siap-siap untuk mangga termanis, langsung dari kebun.",
    hero3Title: "Sayuran Hijau Organik Kini Tersedia",
    hero3Sub: "Dari selada segar hingga bayam, dapatkan asupan hijau harianmu di sini.",
    discoverFarmers: "Temukan Petani di Sekitarmu",
    away: "dari sini",
    freshPicks: "Pilihan Segar & Terlaris",
    viewAll: "Lihat Semua",
    productCatalog: "Katalog Produk",
    browseText: "Jelajahi produk tersergar langsung dari petani lokal.",
    sortBy: "Urutkan: Baru Ditambahkan",
    priceLowHigh: "Harga: Rendah ke Tinggi",
    priceHighLow: "Harga: Tinggi ke Rendah",
    categories: {
      All: "Semua",
      Vegetables: "Sayuran",
      Fruits: "Buah-buahan",
      Grains: "Bijian",
      Spices: "Rempah"
    },
    from: "dari",
    addToCart: "Tambah ke Keranjang",
    noProducts: "Tidak ada produk di kategori ini.",
    viewAllProducts: "Lihat semua produk",
    shoppingCart: "Keranjang Belanja",
    myCart: "Keranjang Saya",
    items: "item",
    product: "Produk",
    price: "Harga",
    quantity: "Jumlah",
    total: "Total",
    orderSummary: "Ringkasan Pesanan",
    subtotal: "Subtotal",
    estimatedShipping: "Estimasi Pengiriman",
    estimatedTaxes: "Pajak",
    grandTotal: "Total Keseluruhan",
    proceedToCheckout: "Lanjut ke Pembayaran",
    continueShopping: "Lanjut Belanja",
    reviews: "ulasan",
    preOrder: "Pre-Order",
    viewProfile: "Lihat Profil",
    welcomeBack: "Selamat datang kembali, berikut ringkasan aktivitas tokomu hari ini.",
    totalSales: "Total Penjualan Hari Ini",
    newOrders: "Pesanan Baru",
    activeBalance: "Saldo Aktif",
    vsYesterday: "vs kemarin",
    vsLastWeek: "vs minggu lalu",
    awaitingDispatch: "menunggu pengiriman",
    commodityTrends: "Tren Harga Komoditas",
    aiInsight: "Wawasan AI",
    aiInsightText: "Harga cabai diprediksi naik 8% dalam 3 hari ke depan.",
    aiInsightSub: "Pertimbangkan menyesuaikan stok atau strategi harga untuk keuntungan maksimal.",
    adjustPricing: "Sesuaikan Harga",
    shipping: "Pengiriman",
    payment: "Pembayaran",
    shippingDetails: "Detail Pengiriman",
    recipientInfo: "Informasi Penerima",
    recipientName: "Nama Penerima",
    phoneNumber: "Nomor Telepon",
    fullAddress: "Alamat Lengkap",
    pinLocation: "Tandai Lokasi Tepat",
    dragPin: "Geser pin atau cari alamatmu untuk pengiriman yang presisi.",
    saveAndContinue: "Simpan dan Lanjutkan",
    securePayment: "Pembayaran Aman",
    selectPayment: "Pilih Metode Pembayaran",
    bankTransfer: "Transfer Bank",
    payBank: "Bayar via transfer bank aman",
    ewallet: "E-Wallet",
    payEwallet: "Bayar dengan GoPay, OVO, dll.",
    confirmPay: "Konfirmasi dan Bayar",
    promo: "Kode Promo (PETANIJAYA)",
    confirmOrder: "Konfirmasi Pesanan",
    shippingTo: "Dikirim ke",
    edit: "Ubah",
    confirmPayment: "Konfirmasi Pembayaran",
    allFarmers: "Semua Petani",
    farmersSubtitle: "Kenalan dengan pahlawan lokal yang menanam makananmu.",
    deliveryDate: "Tanggal Pengiriman",
    deliveryDateNote: "Pilih tanggal pengiriman untuk pre-order (min. 2 hari dari sekarang).",
    addNewProduct: "Tambah Produk Baru",
    auth: {
      welcome: "Selamat Datang di RANTU",
      subtitle: "Menghubungkan Petani Langsung ke Meja Anda",
      login: "Masuk",
      register: "Daftar",
      fullName: "Nama Lengkap",
      email: "Alamat Email",
      password: "Kata Sandi",
      or: "ATAU",
      continueGoogle: "Lanjut dengan Google",
      continueFacebook: "Lanjut dengan Facebook",
      haveAccount: "Sudah punya akun?",
      noAccount: "Belum punya akun?",
      role: "Saya adalah",
      buyer: "Pembeli",
      seller: "Petani/Penjual"
    }
  }
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Tomat Ceri Merah',
    farm: 'Kebun Kerinci',
    price: 25000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?q=80&w=600&auto=format&fit=crop',
    rating: 5,
    reviews: 124,
    tags: ['Organik', 'Baru Panen', 'Sayur'],
    description: "Manis, segar, dan penuh rasa. Ditanam dengan hati-hati di dataran tinggi Kerinci menggunakan benih unggul turun-temurun."
  },
  {
    id: '2',
    name: 'Stroberi Segar',
    farm: 'Kebun Kerinci',
    price: 55000,
    unit: 'kg', 
    image: 'https://images.unsplash.com/photo-1518635017498-87f514b751ba?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviews: 89,
    tags: ['Manis', 'Musiman', 'Buah']
  },
  {
    id: '3',
    name: 'Bayam Hijau',
    farm: "Tani Organik Muaro",
    price: 5000,
    unit: 'ikat',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviews: 65,
    tags: ['Hijau', 'Sehat', 'Sayur']
  },
  {
    id: '4',
    name: 'Jagung Manis',
    farm: "Petani Merangin",
    price: 15000,
    unit: 'pak',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviews: 156,
    tags: ['Segar', 'Manis', 'Sayur', 'Bijian']
  },
  {
    id: '5',
    name: 'Beras Merah Organik',
    farm: "Lumbung Padi Kerinci",
    price: 22000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviews: 32,
    tags: ['Organik', 'Bijian', 'Sehat'],
    description: "Beras merah asli Kerinci yang kaya serat, cocok untuk pola hidup sehat."
  },
  {
    id: '6',
    name: 'Cabai Merah Keriting',
    farm: "Petani Cabai Kumpeh",
    price: 45000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1573809228919-634a70a83350?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviews: 210,
    tags: ['Pedas', 'Rempah', 'Segar'],
    description: "Cabai merah keriting pilihan dengan tingkat kepedasan pas, dipetik langsung dari ladang di Kumpeh."
  }
];
